config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :bookings, only: %i[] do
    resources :reviews, only: [:new, :create]
  end

  resources :bookings, only: :index
  resources :properties, only: %i[index show new create] do
    resources :bookings, only: %i[new create] do
      resources :reviews, only: [:new, :create]
    end
  end
  resources :favorites, only: %i[index create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :property

  has_many :reviews, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user

  validates :rating, presence: true
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @past_bookings = Booking.where(user: current_user, end_date: ...Date.today)
    @future_bookings = Booking.where(user: current_user, start_date: Date.today + 1..)
    @ongoing_bookings = Booking.where(user: current_user, start_date: ..Date.today, end_date: Date.today + 1..)
  end

  def new
    @booking = Booking.new
    @property = Property.find(params[:property_id])
  end

  def create
    @property = Property.find(params[:property_id])

    # start_date = Date.parse(booking_params[:start_date])
    # end_date = Date.parse(booking_params[:end_date])
    # days = (end_date - start_date).to_i + 1

    @booking = current_user.bookings.build(booking_params)
    days = (@booking.end_date - @booking.start_date).to_i
    @booking.property = @property
    @booking.total_price = @property.price_per_night * days
    @booking.status = "confirmed"
    if @booking.save
      redirect_to property_path(@property), notice: "Booked Successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :number_of_guests)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @favorites = Favorite.where(user: current_user)
  end

  # def new
  #   @favorite = favorite.new
  #   @favorite = Property.find(params[:property_id])
  # end

  def create
    @favorite = favorite.new
    @property = Property.find(params[:property_id])
    @favorite.user = current_user
    @favorite.property = @property
    if @favorite.save
      redirect_to property_path(@property), notice: "Added to Wishlist Successfully!"
    else
      render 'new'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @destinations = Property.limit(3)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @properties = Property.all
    @properties = @properties.where("address ILIKE ?", "%#{params[:query]}%") if params[:query].present?

    return unless params[:max_price].present?

    max_price = params[:max_price]

    if max_price == "More than 400"
      @properties = @properties.where("price_per_night > ?", 400)
    else
      max_price = max_price.to_i
      @properties = @properties.where(price_per_night: 0..max_price)
    end
  end

  def show
    @property = Property.find(params[:id])
    @reviews = @property.reviews
    unless @reviews.empty?
      ratings = @reviews.pluck(:rating)
      @avg = (ratings.sum / ratings.length).round
    end
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    @property.user = current_user

    if @property.save
      redirect_to property_path(@property)
    else 
      render :new, status: :unprocessable_entity
    end
  end
  
  private

  def property_params #strong params
    params.require(:property).permit(:title, :capacity, :address, :summary, :price_per_night, :number_of_rooms, :single_room, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
  end
  
  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.user = current_user
    @review.booking = @booking
    if @review.save
      redirect_to property_path(@booking.property)
    else
      render 'new' 
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <h1 class="mb-5">Your bookings</h1>
  <div class="row">
    <% if @future_bookings.present? %>
      <div class="col-12 col-lg-4">
        <h2>Your next trips</h2>
        <% @future_bookings.each do |b| %>
          <%= link_to property_path(b.property), class:"text-decoration-none" do %>
            <div class="card mt-2">
              <div class="card-body">
                <h5 class="card-title"><%= b.property.title %></h5>
                <p class="card-text"><%= b.property.address %></p>
                <ul class="list-unstyled">
                  <li><%= b.start_date %></li>
                  <li><%= b.end_date %></li>
                </ul>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <% if @ongoing_bookings.present? %>
      <div class="col-12 col-lg-4">
        <h2>Current trips</h2>
        <% @ongoing_bookings.each do |b| %>
          <%= link_to property_path(b.property), class:"text-decoration-none" do %>
            <div class="card mt-2">
              <div class="card-body">
                <h5 class="card-title"><%= b.property.title %></h5>
                <p class="card-text"><%= b.property.address %></p>
                <ul class="list-unstyled">
                  <li><%= b.start_date %></li>
                  <li><%= b.end_date %></li>
                </ul>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <% if @past_bookings.present? %>
      <div class="col-12 col-lg-4">
        <h2>Your past bookings</h2>
        <% @past_bookings.each do |b| %>
          <%= link_to property_path(b.property), class:"text-decoration-none" do %>
            <div class="card mt-2">
              <div class="card-body">
                <h5 class="card-title"><%= b.property.title %></h5>
                <p class="card-text"><%= b.property.address %></p>
                <div class="d-flex justify-content-between align-items-end">
                  <ul class="list-unstyled">
                    <li><%= b.start_date %></li>
                    <li><%= b.end_date %></li>
                  </ul>
                  <div>
                    <%= link_to new_booking_review_path(b), class: "btn button btn-primary" do %>
                      <p>Add review</p>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="img-new">
    <div class="row">
      <div class="col-md-6 form-section">
        <h1>Details of your stay</h1>
        <%= simple_form_for [@property, @booking] do |f| %>
          <%= f.input :start_date, placeholder: 'Start date', html5: true %>
          <%= f.input :end_date, placeholder: 'End date', html5: true %>
          <%= f.input :number_of_guests, placeholder: 'How many people'%>
          <%= f.submit class: "btn btn-primary button" %>
        <% end %>
      </div>
      <div class="img-card col-md-3">
        <%= image_tag "img_2.jpg", alt: "travel" %>
      </div>
      <div class="img-card col-md-3">
        <%= image_tag "img_4.jpg", alt: "travel" %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<h1>Your Favorites</h1>

<% @favorites.each do |favorite| %>
  <ul>
    <li><%= favorite.property.title %></li>
  </ul>
<%end%>

app/views/favorites/new.html.erb
<h1>Favorites#new</h1>
<p>Find me in app/views/favorites/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script> %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

     <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="header">
  <h1>Book your favorite place</h1>
  <p>From a cottage in the countryside to a hip apartment in the middle of the city.</P>
</div>

<div class="container">
  <div class="box">
    <h2 class="top-destinations">Latest Top Destinations</h2>
  </div>

  <div class="grid">
    <% @destinations.each do |destination| %>
      <div class="card">
        <%= link_to property_path(destination) do %>
          <div class="card-img" style="background-image: url(<%= cl_image_path destination.photo.key %>)"></div>
        <% end %>
        <div class="card-infos">
          <div>
            <h3><%= destination.title %></h3>
            <%= destination.address %>
          </div>
          <h3>€ <%= destination.price_per_night %></h3>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/properties/index.html.erb
<div class="banner">
  <h2>Book your dream holiday with ease on our website.</h2>
</div>

<div class="container">
  <div class="grid">
    <% @properties.each do |property| %>
      <div class="card">
        <%= link_to property_path(property) do %>
          <div class="card-img" style="background-image: url(<%= cl_image_path property.photo.key %>)"></div>
        <% end %>
        <div class="card-infos">
          <div>
            <h3><%= property.title %></h3>
            <%= property.address %>
          </div>
          <h3>€ <%= property.price_per_night %></h3>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/properties/new.html.erb
<div class="container" class="text-center">
	

<%= simple_form_for @property do |f|%>
  <%= f.input :title, input_html: {class:"rounded w-50"} %>
  <%= f.input :capacity, input_html: {class:"rounded w-50"} %>
  <%= f.input :address, input_html: {class:"rounded w-50"} %>
  <%= f.input :summary, input_html: {class:"rounded w-50"} %>
  <%= f.input :price_per_night, input_html: {class:"rounded w-50"} %>
  <%= f.input :number_of_rooms, input_html: {class:"rounded w-50"} %>
  <%= f.input :single_room %> 
    <%= f.input :photo, as: :file, input_html: {class:"rounded w-50"}%>
<%= f.button :submit, "Submit", class: "button"%>
<% end %>

app/views/properties/show.html.erb
<div class="container">
  <div class="d-flex justify-content-between bg-white">
    <div class=" d-flex justify-content-start prop-info">
    <h1 class="me-2"><%= @property.title %></h1>
      <p class="star-icon me-3 ms-3">
        <% unless @reviews.empty? %>
          <% @avg.times do %>
            <i class="fa-solid fa-star fa-2xs"></i>
          <% end %>
        <% end %>
      </p>
      <p class=""> <%= @reviews.count %> <%= @reviews.count == 1 ? 'Review' : 'Reviews'  %></p>
    </div>
    <div class = "icon-size d-flex justify-content-end mb-2">
      <%= link_to "#", class: "me-3" do%>
        <i class="fa-solid fa-heart icon-size"></i>
      <% end %>
      <%= link_to "#", class: "icon-size" do %>
        <i class="fa-solid fa-message icon-size"></i>
      <% end %>
    </div>
  </div>

  <div class="d-flex card-infos justify-content-between">
    <br>

    <div class="my-5">
      <h2><strong>Located in </strong> <%= @property.address %></h2>
      <h2><strong>Price per Night: </strong>€ <%= @property.price_per_night %></h2>
      <h2><strong>Maximum Capacity: </strong> <%= @property.capacity %></h2>
      <br>
      <div class = "d-flex">
        <%= link_to "Book",  new_property_booking_path(@property), class: "btn button btn-primary me-3"%>
        <% unless Booking.where(user: current_user, property: @property).empty? %>
          <%= link_to "Add Review",  new_booking_review_path(current_user.bookings.last), class: "btn button-review btn-primary me-3"%>
        <% end %>
      </div >
    </div>

    <%= cl_image_tag @property.photo.key, class:"show-img ms-5" %>
  </div>

  <hr>
  <br>
  <div class = "summary">
    <p> <%= @property.summary %></p>
  </div>


  <div class = "d-flex align-items-center">
    <%= image_tag asset_path('host-img.jpg'), class: "host-img me-2"%>
    <div class = "align-items-center pt-3">
      <h3>Owned by</h3>
      <p>John Williams</p>
    </div>
  </div>

  <hr>
  <br>
  <h1>Reviews</h1>
  <br>

  <% @reviews.each do |review|  %>
    <div class="review-card my-2">
      <%#= image_tag asset_path('prof-pic1.jpg')%>

        <% if review.user.email.match(/^(\w|\.)*/)[0].capitalize == "Ahmed" %>
          <%= image_tag asset_path("ahmed-pic.png")%>
        <% elsif review.user.email.match(/^(\w|\.)*/)[0].capitalize == "Yuta" %>
          <%= image_tag asset_path("yuta-pic.jpg")%>
        <% elsif review.user.email.match(/^(\w|\.)*/)[0].capitalize =="Onur" %>
          <%= image_tag asset_path("onur-pic.png")%>
        <% else %>
          <%= image_tag asset_path("jas-pic.jpg")%>
        <% end %>

        <div class="review-card-infos">
          <h2><%= review.user.email.match(/^(\w|\.)*/)[0].capitalize %></h2>
          <p><%= review.comment %></p>
          <div class=" d-flex justify-content-start prop-info">
            <p class="review-icon ms-1"> <% review.rating.times do %>
              <i class="fa-solid fa-star fa-2xs"></i>
            <% end %>
            </p>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
	<h1 style="font-family: 'Boston', sans-serif; font-size: 40px; font-weight: 700; line-height: 50px;">Review</h1>

	<%= simple_form_for [@booking, @review] do |f| %>
		<%= f.input :comment, input_html: {class:"rounded w-50"} %>
		<%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", input_html: {data: {controller: "star-rating"}} %>
		<%= f.button :submit, "Submit", class: "button"%>
	<% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="custom-footer">
  <div class='container'>
    <div class="row justify-content-between">
      <div class="col-sm-4">
        <h4>Find your dream destination</h4>
        <div class="row justify-content-center">
          <div class="col-sm-12 my-6">
            <%= form_with url: properties_path, method: :get, class: "d-flex" do %>
              <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search destination", style: "margin-right: 10px;" %>
              <%= select_tag :max_price,
                options_for_select(
                  [["Max Price", "", disabled: true, selected: true]] +
                  [50, 150, 200, 250, 300, 350, 400, "> 400"].map { |price| ["#{price} €", price] },
                  params[:max_price]
                ),
                class: "form-control smaller-input",
                style: "margin-right: 10px;"
              %>
              <%= submit_tag "Search", name: "", class: "btn btn-primary button" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <h4>Follow Us</h4>
        <ul class="list-inline social-icons">
          <li class="list-inline-item"><i class="fab fa-facebook" style="font-size: 35px;"></i></li>
          <li class="list-inline-item"><i class="fab fa-twitter" style="font-size: 35px;"></i></li>
          <li class="list-inline-item"><i class="fab fa-instagram" style="font-size: 35px;"></i></li>
        </ul>
      </div>
      <h4>Links</h4>
      <div class="row">
        <div class="col-sm-6" style="width: 180px;">
          <ul class="list-unstyled">
            <li><span class="footer-link">About Us</span></li>
            <li><span class="footer-link">Contact</span></li>
            <li><span class="footer-link">Bookings</span></li>
          </ul>
        </div>
        <div class="col-sm-6" style="width: 180px;">
          <ul class="list-unstyled">
            <li><span class="footer-link">Favorites</span></li>
            <li><span class="footer-link">Home Owner</span></li>
            <li><span class="footer-link">Work for Us</span></li>
          </ul>
        </div>
      </div>


      </div>
    </div>
    <hr>
    <div class="row justify-content-center">
      <div class="col-sm-6 text-center">
        <%= image_tag "logo_project.png", alt: "Logo", style: "max-height: 100px;" %>
        <p>&copy; 2023 Your Company. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div class="logo-container">
        <%= image_tag ('logo_project.png'), style: 'width: 80px;' %>
        <p>Airbnb</p>
      </div>
    <% end %>

    <div class="row justify-content-center">
      <div class="col-sm-12 my-6">
        <%= form_with url: properties_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search destination", style: "margin-right: 10px;" %>
          <%= select_tag :max_price,
            options_for_select(
              [["Max Price", "", disabled: true, selected: true]] +
              [50, 150, 200, 250, 300, 350, 400, "> 400"].map { |price| ["#{price} €", price] },
              params[:max_price]
            ),
            class: "form-control smaller-input",
            style: "margin-right: 10px;"
          %>
          <%= submit_tag "Search", name: "", class: "btn btn-primary button" %>
        <% end %>
      </div>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My booking", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Property", new_property_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">

            <% if current_user.email.match(/^(\w|\.)*/)[0].capitalize == "Ahmed" %>
              <%= image_tag "ahmed-pic.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% elsif current_user.email.match(/^(\w|\.)*/)[0].capitalize == "Yuta" %>
              <%= image_tag "yuta-pic.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% elsif current_user.email.match(/^(\w|\.)*/)[0].capitalize =="Onur" %>
              <%= image_tag "onur-pic.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "jas-pic.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>


            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "About us", "#", class: "dropdown-item action-link" %>
              <%= link_to "Contact us", "#", class: "dropdown-item action-link" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item action-link", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>